hmdb51_actions = [
    "flic flac",
    "hit",
    "run",
    "kiss",
    "talk",
    "shoot bow",
    "eat",
    "stand",
    "shoot gun",
    "kick",
    "situp",
    "pick",
    "somersault",
    "golf",
    "clap",
    "draw sword",
    "handstand",
    "wave",
    "brush hair",
    "shoot ball",
    "pullup",
    "fencing",
    "laugh",
    "smile",
    "turn",
    "climb",
    "climb stairs",
    "chew",
    "smoke",
    "ride bike",
    "sword",
    "fall floor",
    "drink",
    "hug",
    "cartwheel",
    "punch",
    "jump",
    "pushup",
    "push",
    "ride horse",
    "swing baseball",
    "throw",
    "dribble",
    "sit",
    "kick ball",
    "dive",
    "pour",
    "catch",
    "sword exercise",
    "shake hands",
    "walk",]

ucf101_actions = [
"Typing",
    "Rowing",
    "Punch",
    "High Jump",
    "Hand stand Pushups",
    "Nunchucks",
    "Cliff Diving",
    "Swing",
    "Frisbee Catch",
    "Sumo Wrestling",
    "Yo Yo",
    "Lunges",
    "Clean And Jerk",
    "Skate Boarding",
    "Rope Climbing",
    "Playing Piano",
    "Tennis Swing",
    "Juggling Balls",
    "Military Parade",
    "Haircut",
    "Volleyball Spiking",
    "Soccer Penalty",
    "Floor Gymnastics",
    "Billiards",
    "Cricket Bowling",
    "Hammering",
    "Cutting In Kitchen",
    "Shotput",
    "Playing Tabla",
    "Mopping Floor",
    "Hammer Throw",
    "Fencing",
    "Trampoline Jumping",
    "Archery",
    "Rafting",
    "Writing On Board",
    "Javelin Throw",
    "Bowling",
    "Drumming",
    "Skijet",
    "Pull Ups",
    "Apply Lipstick",
    "Baby Crawling",
    "Table Tennis Shot",
    "Long Jump",
    "Body Weight Squats",
    "Mixing",
    "Playing Dhol",
    "Tai Chi",
    "Parallel Bars",
    "Soccer Juggling",
    "Cricket Shot",
    "Pommel Horse",
    "Hula Hoop",
    "Playing Violin",
    "Walking With Dog",
    "Knitting",
    "Boxing Speed Bag",
    "Uneven Bars",
    "Sky Diving",
    "Jumping Jack",
    "Shaving Beard",
    "Salsa Spin",
    "Brushing Teeth",
    "Wall Pushups",
    "Baseball Pitch",
    "Horse Riding",
    "Throw Discus",
    "Push Ups",
    "Field Hockey Penalty",
    "Golf Swing",
    "Jump Rope",
    "Breast Stroke",
    "Playing Cello",
    "Blowing Candles",
    "Playing Daf",
    "Playing Flute",
    "Horse Race",
    "Balance Beam",
    "Skiing",
    "Front Crawl",
    "Handstand Walking",
    "Head Massage",
    "Basketball",
    "Basketball Dunk",
    "Ice Dancing",
    "Rock Climbing Indoor",
    "Diving",
    "Pole Vault",
    "Kayaking",
    "Apply Eye Makeup",
    "Bench Press",
    "Boxing Punching Bag",
    "Playing Guitar",
    "Biking",
    "Still Rings",
    "Pizza Tossing",
    "Surfing",
    "Playing Sitar",
    "Blow Dry Hair",
    "Band Marching"
]

k400_actions = [
" abseiling",
" air drumming",
" answering questions",
" applauding",
" applying cream",
" archery",
" arm wrestling",
" arranging flowers",
" assembling computer",
" auctioning",
" baby waking up",
" baking cookies",
" balloon blowing",
" bandaging",
" barbequing",
" bartending",
" beatboxing",
" bee keeping",
" belly dancing",
" bench pressing",
" bending back",
" bending metal",
" biking through snow",
" blasting sand",
" blowing glass",
" blowing leaves",
" blowing nose",
" blowing out candles",
" bobsledding",
" bookbinding",
" bouncing on trampoline",
" bowling",
" braiding hair",
" breading or breadcrumbing",
" breakdancing",
" brush painting",
" brushing hair",
" brushing teeth",
" building cabinet",
" building shed",
" bungee jumping",
" busking",
" canoeing or kayaking",
" capoeira",
" carrying baby",
" cartwheeling",
" carving pumpkin",
" catching fish",
" catching or throwing baseball",
" catching or throwing frisbee",
" catching or throwing softball",
" celebrating",
" changing oil",
" checking tires",
" cheerleading",
" chopping wood",
" clapping",
" clay pottery making",
" clean and jerk",
" cleaning floor",
" cleaning gutters",
" cleaning pool",
" cleaning shoes",
" cleaning toilet",
" cleaning windows",
" climbing a rope",
" climbing ladder",
" climbing tree",
" contact juggling",
" cooking chicken",
" cooking egg",
" cooking on campfire",
" cooking sausages",
" counting money",
" country line dancing",
" cracking neck",
" crawling baby",
" crossing river",
" crying",
" curling hair",
" cutting nails",
" cutting pineapple",
" cutting watermelon",
" dancing ballet",
" dancing charleston",
" dancing gangnam style",
" dancing macarena",
" deadlifting",
" decorating the christmas tree",
" digging",
" dining",
" disc golfing",
" diving cliff",
" dodgeball",
" doing aerobics",
" doing laundry",
" doing nails",
" drawing",
" dribbling basketball",
" drinking",
" drinking beer",
" drinking shots",
" driving car",
" driving tractor",
" drop kicking",
" drumming fingers",
" dunking basketball",
" dying hair",
" eating burger",
" eating cake",
" eating carrots",
" eating chips",
" eating doughnuts",
" eating hotdog",
" eating ice cream",
" eating spaghetti",
" eating watermelon",
" egg hunting",
" exercising arm",
" exercising with an exercise ball",
" extinguishing fire",
" faceplanting",
" feeding birds",
" feeding fish",
" feeding goats",
" filling eyebrows",
" finger snapping",
" fixing hair",
" flipping pancake",
" flying kite",
" folding clothes",
" folding napkins",
" folding paper",
" front raises",
" frying vegetables",
" garbage collecting",
" gargling",
" getting a haircut",
" getting a tattoo",
" giving or receiving award",
" golf chipping",
" golf driving",
" golf putting",
" grinding meat",
" grooming dog",
" grooming horse",
" gymnastics tumbling",
" hammer throw",
" headbanging",
" headbutting",
" high jump",
" high kick",
" hitting baseball",
" hockey stop",
" holding snake",
" hopscotch",
" hoverboarding",
" hula hooping",
" hurdling",
" hurling",
" ice climbing",
" ice fishing",
" ice skating",
" ironing",
" javelin throw",
" jetskiing",
" jogging",
" juggling balls",
" juggling fire",
" juggling soccer ball",
" jumping into pool",
" jumpstyle dancing",
" kicking field goal",
" kicking soccer ball",
" kissing",
" kitesurfing",
" knitting",
" krumping",
" laughing",
" laying bricks",
" long jump",
" lunge",
" making a cake",
" making a sandwich",
" making bed",
" making jewelry",
" making pizza",
" making snowman",
" making sushi",
" making tea",
" marching",
" massaging back",
" massaging feet",
" massaging legs",
" massaging person",
" milking cow",
" mopping floor",
" motorcycling",
" moving furniture",
" mowing lawn",
" news anchoring",
" opening present",
" paragliding",
" parasailing",
" parkour",
" passing american football",
" peeling apples",
" peeling potatoes",
" petting animal",
" petting cat",
" picking fruit",
" planting trees",
" plastering",
" playing accordion",
" playing badminton",
" playing bagpipes",
" playing basketball",
" playing bass guitar",
" playing cards",
" playing cello",
" playing chess",
" playing clarinet",
" playing controller",
" playing cricket",
" playing cymbals",
" playing didgeridoo",
" playing drums",
" playing flute",
" playing guitar",
" playing harmonica",
" playing harp",
" playing ice hockey",
" playing keyboard",
" playing kickball",
" playing monopoly",
" playing organ",
" playing paintball",
" playing piano",
" playing poker",
" playing recorder",
" playing saxophone",
" playing squash or racquetball",
" playing tennis",
" playing trombone",
" playing trumpet",
" playing ukulele",
" playing violin",
" playing volleyball",
" playing xylophone",
" pole vault",
" presenting weather forecast",
" pull ups",
" pumping fist",
" pumping gas",
" punching bag",
" punching person",
" push up",
" pushing car",
" pushing cart",
" pushing wheelchair",
" reading book",
" reading newspaper",
" recording music",
" riding a bike",
" riding camel",
" riding elephant",
" riding mechanical bull",
" riding mountain bike",
" riding mule",
" riding or walking with horse",
" riding scooter",
" riding unicycle",
" ripping paper",
" robot dancing",
" rock climbing",
" rock scissors paper",
" roller skating",
" running on treadmill",
" sailing",
" salsa dancing",
" sanding floor",
" scrambling eggs",
" scuba diving",
" setting table",
" shaking hands",
" shaking head",
" sharpening knives",
" sharpening pencil",
" shaving head",
" shaving legs",
" shearing sheep",
" shining shoes",
" shooting basketball",
" shooting goal",
" shot put",
" shoveling snow",
" shredding paper",
" shuffling cards",
" side kick",
" sign language interpreting",
" singing",
" situp",
" skateboarding",
" ski jumping",
" skiing",
" skiing crosscountry",
" skiing slalom",
" skipping rope",
" skydiving",
" slacklining",
" slapping",
" sled dog racing",
" smoking",
" smoking hookah",
" snatch weight lifting",
" sneezing",
" sniffing",
" snorkeling",
" snowboarding",
" snowkiting",
" snowmobiling",
" somersaulting",
" spinning poi",
" spray painting",
" spraying",
" springboard diving",
" squat",
" sticking tongue out",
" stomping grapes",
" stretching arm",
" stretching leg",
" strumming guitar",
" surfing crowd",
" surfing water",
" sweeping floor",
" swimming backstroke",
" swimming breast stroke",
" swimming butterfly stroke",
" swing dancing",
" swinging legs",
" swinging on something",
" sword fighting",
" tai chi",
" taking a shower",
" tango dancing",
" tap dancing",
" tapping guitar",
" tapping pen",
" tasting beer",
" tasting food",
" testifying",
" texting",
" throwing axe",
" throwing discus",
" tickling",
" tobogganing",
" tossing coin",
" tossing salad",
" training dog",
" trapezing",
" trimming or shaving beard",
" trimming trees",
" triple jump",
" tying bow tie",
" tying knot",
" tying tie",
" unboxing",
" unloading truck",
" using computer",
" using remote controller",
" using segway",
" vault",
" waiting in line",
" walking the dog",
" washing dishes",
" washing feet",
" washing hair",
" washing hands",
" water skiing",
" water sliding",
" watering plants",
" waxing back",
" waxing chest",
" waxing eyebrows",
" waxing legs",
" weaving basket",
" welding",
" whistling",
" windsurfing",
" wrapping present",
" wrestling",
" writing",
" yawning",
" yoga",
" zumba",
]

k600_actions = [
    "tying knot (not on a tie)",
    "swinging baseball bat",
    "playing ocarina",
    "waiting in line",
    "land sailing",
    "snowboarding",
    "disc golfing",
    "cleaning toilet",
    "eating doughnuts",
    "poking bellybutton",
    "situp",
    "petting animal (not cat)",
    "doing nails",
    "jetskiing",
    "doing jigsaw puzzle",
    "drop kicking",
    "somersaulting",
    "skiing slalom",
    "hurling (sport)",
    "battle rope training",
    "extinguishing fire",
    "krumping",
    "knitting",
    "making snowman",
    "punching bag",
    "opening wine bottle",
    "flying kite",
    "making a cake",
    "bobsledding",
    "playing violin",
    "breading or breadcrumbing",
    "throwing water balloon",
    "hoverboarding",
    "changing wheel (not on bike)",
    "playing accordion",
    "folding napkins",
    "skydiving",
    "climbing a rope",
    "arranging flowers",
    "fencing (sport)",
    "fixing hair",
    "scrapbooking",
    "tagging graffiti",
    "scuba diving",
    "jumping jacks",
    "belly dancing",
    "bottling",
    "testifying",
    "capsizing",
    "catching fish",
    "playing lute",
    "dining",
    "mowing lawn",
    "high kick",
    "shooting goal (soccer)",
    "cracking back",
    "embroidering",
    "ironing",
    "giving or receiving award",
    "crawling baby",
    "rope pushdown",
    "wading through water",
    "braiding hair",
    "playing field hockey",
    "sausage making",
    "decorating the christmas tree",
    "licking",
    "news anchoring",
    "riding mechanical bull",
    "clay pottery making",
    "eating spaghetti",
    "watching tv",
    "pouring beer",
    "historical reenactment",
    "kitesurfing",
    "writing",
    "feeding birds",
    "playing bass guitar",
    "hammer throw",
    "building lego",
    "shucking oysters",
    "motorcycling",
    "wrapping present",
    "using inhaler",
    "spray painting",
    "playing darts",
    "hurdling",
    "clam digging",
    "waxing back",
    "raising eyebrows",
    "washing hair",
    "busking",
    "wading through mud",
    "tiptoeing",
    "catching or throwing softball",
    "photobombing",
    "trimming or shaving beard",
    "playing volleyball",
    "bouncing on trampoline",
    "laying concrete",
    "dyeing hair",
    "laying bricks",
    "dancing charleston",
    "fly tying",
    "grinding meat",
    "eating cake",
    "playing dominoes",
    "finger snapping",
    "blowing nose",
    "holding snake",
    "getting a piercing",
    "faceplanting",
    "polishing metal",
    "flint knapping",
    "playing rubiks cube",
    "front raises",
    "lock picking",
    "using a wrench",
    "ironing hair",
    "riding or walking with horse",
    "peeling potatoes",
    "throwing snowballs",
    "making tea",
    "crying",
    "casting fishing line",
    "ice fishing",
    "trapezing",
    "parasailing",
    "shaking hands",
    "catching or throwing frisbee",
    "swimming butterfly stroke",
    "high jump",
    "springboard diving",
    "playing poker",
    "shuffling feet",
    "bungee jumping",
    "falling off chair",
    "playing tennis",
    "smoking",
    "cleaning gutters",
    "home roasting coffee",
    "spinning poi",
    "chopping meat",
    "brush painting",
    "sawing wood",
    "using segway",
    "smelling feet",
    "roasting pig",
    "using circular saw",
    "bathing dog",
    "dribbling basketball",
    "blowing bubble gum",
    "shearing sheep",
    "cutting orange",
    "using a power drill",
    "snowkiting",
    "shaking head",
    "using a microscope",
    "dyeing eyebrows",
    "playing paintball",
    "playing hand clapping games",
    "dancing gangnam style",
    "playing kickball",
    "roasting marshmallows",
    "jogging",
    "stomping grapes",
    "jumping bicycle",
    "juggling fire",
    "playing clarinet",
    "sticking tongue out",
    "getting a tattoo",
    "pillow fight",
    "side kick",
    "square dancing",
    "wood burning (art)",
    "staring",
    "steer roping",
    "grooming horse",
    "blowing out candles",
    "carving ice",
    "playing squash or racquetball",
    "ice climbing",
    "playing keyboard",
    "climbing ladder",
    "putting on foundation",
    "driving tractor",
    "cutting nails",
    "cracking knuckles",
    "pushing wheelbarrow",
    "cracking neck",
    "threading needle",
    "answering questions",
    "bench pressing",
    "dancing macarena",
    "trimming shrubs",
    "eating chips",
    "playing monopoly",
    "leatherworking",
    "changing gear in car",
    "massaging back",
    "sword swallowing",
    "texting",
    "jaywalking",
    "blowing leaves",
    "moving furniture",
    "brushing hair",
    "blowdrying hair",
    "inflating balloons",
    "sword fighting",
    "ripping paper",
    "cheerleading",
    "dumpster diving",
    "playing controller",
    "golf driving",
    "opening door",
    "rock scissors paper",
    "mosh pit dancing",
    "tapping guitar",
    "kissing",
    "winking",
    "carving pumpkin",
    "hula hooping",
    "using puppets",
    "contact juggling",
    "playing basketball",
    "throwing ball (not baseball or american football)",
    "wrestling",
    "falling off bike",
    "presenting weather forecast",
    "drinking shots",
    "head stand",
    "crossing river",
    "needle felting",
    "preparing salad",
    "yoga",
    "scrubbing face",
    "breathing fire",
    "bookbinding",
    "eating hotdog",
    "sleeping",
    "smoking pipe",
    "riding a bike",
    "weaving basket",
    "water sliding",
    "weaving fabric",
    "bandaging",
    "whistling",
    "playing cymbals",
    "riding unicycle",
    "juggling balls",
    "headbanging",
    "waxing chest",
    "welding",
    "bending back",
    "cleaning shoes",
    "water skiing",
    "tying bow tie",
    "shuffling cards",
    "alligator wrestling",
    "tickling",
    "playing organ",
    "dancing ballet",
    "unboxing",
    "kicking soccer ball",
    "surfing crowd",
    "triple jump",
    "pushing cart",
    "playing ping pong",
    "skipping stone",
    "applauding",
    "delivering mail",
    "separating eggs",
    "swing dancing",
    "golf chipping",
    "hockey stop",
    "bodysurfing",
    "playing polo",
    "stretching leg",
    "rolling pastry",
    "washing hands",
    "playing bagpipes",
    "riding camel",
    "hugging (not baby)",
    "longboarding",
    "riding elephant",
    "washing feet",
    "tackling",
    "yawning",
    "reading book",
    "massaging feet",
    "packing",
    "shaving legs",
    "riding snow blower",
    "planting trees",
    "driving car",
    "curling hair",
    "sucking lolly",
    "surfing water",
    "bee keeping",
    "shining flashlight",
    "card throwing",
    "using atm",
    "long jump",
    "clapping",
    "chopping wood",
    "playing maracas",
    "chopping vegetables",
    "laughing",
    "making paper aeroplanes",
    "swimming breast stroke",
    "parkour",
    "sled dog racing",
    "opening bottle (not wine)",
    "pushing car",
    "bull fighting",
    "watering plants",
    "sanding floor",
    "lawn mower racing",
    "beatboxing",
    "tap dancing",
    "playing harp",
    "mountain climber (exercise)",
    "stretching arm",
    "tie dying",
    "snatch weight lifting",
    "robot dancing",
    "cutting pineapple",
    "cooking on campfire",
    "geocaching",
    "carrying baby",
    "visiting the zoo",
    "hitting baseball",
    "jumpstyle dancing",
    "coloring in",
    "building shed",
    "playing scrabble",
    "doing aerobics",
    "drumming fingers",
    "drooling",
    "making a sandwich",
    "petting cat",
    "blasting sand",
    "dodgeball",
    "assembling bicycle",
    "eating ice cream",
    "shoveling snow",
    "kicking field goal",
    "playing blackjack",
    "cooking scallops",
    "building sandcastle",
    "tasting wine",
    "twiddling fingers",
    "tying shoe laces",
    "juggling soccer ball",
    "sign language interpreting",
    "playing netball",
    "hopscotch",
    "ice swimming",
    "recording music",
    "clean and jerk",
    "marching",
    "opening present",
    "shaving head",
    "slacklining",
    "shining shoes",
    "capoeira",
    "making sushi",
    "building cabinet",
    "tossing coin",
    "folding paper",
    "shopping",
    "opening refrigerator",
    "tai chi",
    "swimming front crawl",
    "photocopying",
    "sweeping floor",
    "talking on cell phone",
    "repairing puncture",
    "doing laundry",
    "spelunking",
    "making horseshoes",
    "laying stone",
    "playing ice hockey",
    "changing oil",
    "putting on mascara",
    "playing piano",
    "playing recorder",
    "snowmobiling",
    "planing wood",
    "blowing glass",
    "getting a haircut",
    "arm wrestling",
    "pinching",
    "auctioning",
    "person collecting garbage",
    "putting on lipstick",
    "playing pan pipes",
    "passing american football (in game)",
    "massaging legs",
    "running on treadmill",
    "tapping pen",
    "ski jumping",
    "drawing",
    "burping",
    "playing harmonica",
    "luge",
    "sneezing",
    "cutting apple",
    "tightrope walking",
    "roller skating",
    "docking boat",
    "headbutting",
    "trimming trees",
    "reading newspaper",
    "base jumping",
    "using a paint roller",
    "air drumming",
    "flipping pancake",
    "shooting basketball",
    "karaoke",
    "abseiling",
    "eating watermelon",
    "shaping bread dough",
    "barbequing",
    "walking the dog",
    "fidgeting",
    "putting on shoes",
    "playing didgeridoo",
    "washing dishes",
    "cooking egg",
    "cleaning windows",
    "catching or throwing baseball",
    "mopping floor",
    "paragliding",
    "gold panning",
    "bouncing on bouncy castle",
    "cutting watermelon",
    "cosplaying",
    "playing chess",
    "massaging person's head",
    "country line dancing",
    "crossing eyes",
    "zumba",
    "breaking boards",
    "sharpening pencil",
    "rock climbing",
    "making balloon shapes",
    "eating burger",
    "gospel singing in church",
    "tying necktie",
    "cartwheeling",
    "jumping into pool",
    "laying tiles",
    "adjusting glasses",
    "grooming dog",
    "chiseling stone",
    "bending metal",
    "pole vault",
    "attending conference",
    "sailing",
    "throwing axe",
    "deadlifting",
    "playing trombone",
    "backflip (human)",
    "making cheese",
    "lunge",
    "playing cricket",
    "playing xylophone",
    "fixing bicycle",
    "making bubbles",
    "push up",
    "waxing legs",
    "riding scooter",
    "throwing tantrum",
    "exercising with an exercise ball",
    "golf putting",
    "curling (sport)",
    "playing gong",
    "passing american football (not in game)",
    "peeling apples",
    "picking fruit",
    "squat",
    "slapping",
    "using a sledge hammer",
    "archery",
    "shot put",
    "throwing knife",
    "tango dancing",
    "riding mule",
    "passing soccer ball",
    "smoking hookah",
    "playing drums",
    "pushing wheelchair",
    "pirouetting",
    "playing pinball",
    "unloading truck",
    "dunking basketball",
    "cleaning pool",
    "sipping cup",
    "sharpening knives",
    "putting in contact lenses",
    "arguing",
    "counting money",
    "plastering",
    "making the bed",
    "putting on eyeliner",
    "walking through snow",
    "diving cliff",
    "gymnastics tumbling",
    "installing carpet",
    "tasting food",
    "making jewelry",
    "climbing tree",
    "javelin throw",
    "playing ukulele",
    "directing traffic",
    "lighting fire",
    "playing marbles",
    "calligraphy",
    "playing with trains",
    "canoeing or kayaking",
    "snorkeling",
    "setting table",
    "brushing teeth",
    "mushroom foraging",
    "ice skating",
    "bulldozing",
    "biking through snow",
    "singing",
    "punching person (boxing)",
    "swinging on something",
    "lifting hat",
    "milking cow",
    "swimming backstroke",
    "using remote controller (not gaming)",
    "card stacking",
    "pumping fist",
    "chiseling wood",
    "tasting beer",
    "playing guitar",
    "looking at phone",
    "feeding goats",
    "checking tires",
    "playing trumpet",
    "pumping gas",
    "skiing mono",
    "cumbia",
    "windsurfing",
    "waving hand",
    "assembling computer",
    "eating carrots",
    "sewing",
    "baking cookies",
    "hand washing clothes",
    "making pizza",
    "waxing eyebrows",
    "playing flute",
    "pull ups",
    "bartending",
    "standing on hands",
    "skateboarding",
    "putting on sari",
    "egg hunting",
    "playing saxophone",
    "vacuuming floor",
    "archaeological excavation",
    "breakdancing",
    "throwing discus",
    "playing laser tag",
    "playing badminton",
    "chewing gum",
    "moon walking",
    "skiing crosscountry",
    "playing beer pong",
    "combing hair",
    "yarn spinning",
    "acting in play",
    "hugging baby",
    "cooking sausages (not on barbeque)",
    "training dog",
    "calculating",
    "applying cream",
    "scrambling eggs",
    "salsa dancing",
    "celebrating",
    "folding clothes",
    "playing cello",
    "using bagging machine",
    "marriage proposal",
    "feeding fish",
    "huddling",
    "bowling",
    "frying vegetables",
    "waking up",
    "skipping rope",
    "tobogganing",
    "popping balloons",
    "massaging neck",
    "smashing",
    "contorting",
]

# define a function to find some actions repeated in one dataset and print the repeated actions
def find_repeated_actions(actions):
    repeated_actions = []
    for action in actions:
        if actions.count(action) > 1:
            repeated_actions.append(action)
    print(repeated_actions)
    return repeated_actions

# find the repeated actions in the k600 dataset
repeated_actions = find_repeated_actions(k600_actions)